### ISSUE TITLE
Adding gulp-webserver

### ISSUE THREAD

**Issue by GerardSoleCa** [Textalk/angular-schema-form-bootstrap#2]
Hello,

I'm PR to add a gulp task which serves this repository. It makes really easy to test changes using the examples.

Used along with watch makes an incredible way to see how changes affects the forms.

In order to use, just call "gulp serve".

Gerard.

**Comment by jimmycasey** [comment]
Hi @GerardSoleCa ,

So what commands do I need to run to test and debug locally?

Thanks
